package http

import (
	"fmt"
	"net/http"
	"strings"
)

type traefikRouteData struct {
	ID         int64
	Name       string
	Hostname   string
	Domain     string
	ServiceName string
	Port       int
	Middleware string
}

type traefikPageData struct {
	Domain     string
	Email      string
	HTTPEntrypoint  string
	HTTPSEntrypoint string
	Network    string
	Routes     []traefikRouteData
	RouteCount int
	YAML       string
	CSRFToken  string
	Username   string
}

func (s *Server) traefikPage(w http.ResponseWriter, r *http.Request) {
	cfg, err := s.settings.Get()
	if err != nil {
		s.render.RenderError(w, r, 500, "Failed to load settings")
		return
	}

	projects, err := s.projects.List()
	if err != nil {
		s.render.RenderError(w, r, 500, "Failed to load projects")
		return
	}

	var routes []traefikRouteData
	for _, p := range projects {
		if p.TraefikHostname == "" {
			continue
		}
		serviceName := strings.ReplaceAll(p.Name, "_", "-")
		routes = append(routes, traefikRouteData{
			ID:          p.ID,
			Name:        p.Name,
			Hostname:    p.TraefikHostname,
			Domain:      cfg.TraefikDomain,
			ServiceName: serviceName,
			Port:        p.TraefikPort,
			Middleware:  p.TraefikMiddleware,
		})
	}

	pageDomain := cfg.TraefikDomain
	if pageDomain == "" {
		pageDomain = "mydomain.com"
	}
	pageEmail := cfg.TraefikEmail
	if pageEmail == "" {
		pageEmail = "admin@example.com"
	}
	httpEntry := cfg.TraefikHTTPEntrypoint
	if httpEntry == "" {
		httpEntry = "web"
	}
	httpsEntry := cfg.TraefikHTTPSEntrypoint
	if httpsEntry == "" {
		httpsEntry = "websecure"
	}
	network := cfg.TraefikNetwork
	if network == "" {
		network = "traefik"
	}

	yaml := generateTraefikYAML(routes, pageDomain, pageEmail, httpEntry, httpsEntry, network)

	username := s.auth.GetUsername(r)
	s.render.Render(w, r, "traefik.html", traefikPageData{
		Domain:          pageDomain,
		Email:           pageEmail,
		HTTPEntrypoint:  httpEntry,
		HTTPSEntrypoint: httpsEntry,
		Network:         network,
		Routes:          routes,
		RouteCount:      len(routes),
		YAML:            yaml,
		CSRFToken:       s.csrfToken(r),
		Username:        username,
	})
}

func generateTraefikYAML(routes []traefikRouteData, domain, email, httpEntry, httpsEntry, network string) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf(`# Traefik dynamic config for %s
# Generated by DeployHub
---
`))

	if email != "" {
		b.WriteString(fmt.Sprintf("tls:\n  certResolvers:\n    letsencrypt:\n      acme:\n        email: %s\n        storage: /letsencrypt/acme.json\n        httpChallenge:\n          entryPoint: %s\n\n", email, httpEntry))
	} else {
		b.WriteString("tls:\n  certResolvers:\n    letsencrypt:\n      acme:\n        storage: /letsencrypt/acme.json\n        httpChallenge:\n          entryPoint: web\n\n")
	}

	b.WriteString("http:\n  routers:\n")

	for _, r := range routes {
		routerName := strings.ReplaceAll(r.Name, "_", "-")
		fullHostname := r.Hostname + "." + domain
		port := r.Port
		if port == 0 {
			port = 80
		}

		b.WriteString(fmt.Sprintf(`    %s:
      rule: "Host(\`+"`"+`%s\`+"`"+`")"
      entrypoints:
        - %s
      service: %s
      tls:
        certResolver: letsencrypt
`, routerName, fullHostname, httpsEntry, routerName))

		if r.Middleware != "" {
			middlewares := strings.Split(r.Middleware, ",")
			for i, m := range middlewares {
				middlewares[i] = strings.TrimSpace(m)
			}
			b.WriteString(fmt.Sprintf(`      middlewares:
%s
`, indentList(middlewares, 8)))
		}
	}

	b.WriteString("\n  services:\n")
	for _, r := range routes {
		serviceName := strings.ReplaceAll(r.Name, "_", "-")
		port := r.Port
		if port == 0 {
			port = 80
		}

		b.WriteString(fmt.Sprintf(`    %s:
      loadBalancer:
        servers:
          - url: "http://%s:%d"
`, serviceName, serviceName, port))
	}

	return b.String()
}

func indentList(items []string, indent int) string {
	if len(items) == 0 {
		return ""
	}
	prefix := strings.Repeat(" ", indent)
	quoted := make([]string, len(items))
	for i, item := range items {
		quoted[i] = prefix + "- " + item
	}
	return strings.Join(quoted, "\n")
}
